services:

  db:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:  # Cargar variables desde el archivo .env
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:80
volumes:
  mariadb_data:
